DROP VIEW IF EXISTS public.dim_outcomes;
CREATE OR REPLACE VIEW public.dim_outcomes
AS
SELECT
  EI.EVENT_DESC, E.UPDATE_DATE, EI.START_DATE, EI.END_DATE, E.AMOUNT, 
  CASE
    WHEN PI.CARD_TYPE_ID = 1 THEN PI.PAYMENT_LIMIT_DAY
    ELSE EI.PAYMENT_DAY
  END PAYMENT_DAY,
  EI.IND_ACTIVE, BI.BANK_DESC, CT.CARD_TYPE_DESC,
  R.RECURRENCE_DESC
FROM stg.EVENT_INFORMATION EI
LEFT JOIN stg.EVENT E
ON EI.USER_ID = E.USER_ID
  AND EI.EVENT_ID = E.EVENT_ID
LEFT JOIN stg.EVENT_TYPE ET
ON EI.EVENT_TYPE = ET.ID
LEFT JOIN stg.PAYMENT_INFORMATION PI
ON EI.PAYMENT_ID = PI.PAYMENT_ID
LEFT JOIN stg.BANK_INFORMATION BI
ON PI.BANK_ID = BI.BANK_ID
LEFT JOIN stg.CARD_TYPES CT
ON PI.CARD_TYPE_ID = CT.CARD_TYPE_ID
LEFT JOIN stg.RECURRENCES R
ON EI.RECURRENCE = R.RECURRENCE_ID
WHERE
  EI.USER_ID = 1
   AND EI.EVENT_TYPE = 1
ORDER BY E.UPDATE_DATE
;