SELECT * FROM users;
SELECT * FROM recurrences;
SELECT * FROM bank_information;
SELECT * FROM card_types;
SELECT * FROM payment_information;
SELECT * FROM incomes_information;
SELECT * FROM outcomes_information;
SELECT * FROM incomes;
SELECT * FROM outcomes;